[package]
name = "query_graph_nodes"
version = "0.1.0"
edition = "2021"

[dependencies]
altius-revm.workspace = true
revm-primitives.workspace = true
serde_json = "1.0"

[[bin]]
name = "query_graph_nodes"
path = "src/main.rs"
